// ─────────────────────────────────────────────────────────────────────────────
//  Card data for "Погані Картки" (Cards Against Humanity UA edition)
//  Black cards: use _ as a blank placeholder.
//  White cards: short nouns / phrases that fill the blanks.
// ─────────────────────────────────────────────────────────────────────────────

export const blackCards: string[] = [
  // single-blank
  "Вчені нарешті з'ясували, що викликає депресію. Це — _.",
  "Мій дід казав: «Найгірше в житті — це _.»",
  "На День народження мені подарували _. Це був найкращий подарунок.",
  "_ — ось що справді об'єднує українців.",
  "У новинах: «Верховна Рада проголосувала за легалізацію _.»",
  "Чому я завжди забуваю купити хліб? Бо думаю про _.",
  "Дієтологи рекомендують замінити цукор на _.",
  "Новий стартап обіцяє вирішити всі проблеми людства за допомогою _.",
  "Моя мама думає, що я займаюся _, а насправді — грю в карти.",
  "За даними соціологів, 73% українців найбільше бояться _.",
  "Мій кіт дивиться на мене так, ніби знає про _.",
  "У моєму заповіті написано: «Замість вінків прошу принести _.»",
  "Нова валюта майбутнього — _.",
  "Перед сном я завжди молюся про те, щоб _ зникло з мого життя.",
  "Секрет довгого шлюбу: ніколи не згадувати про _.",
  "ШІ навчився всього людського, включаючи _.",
  "Психолог сказав, що в корені всіх моїх проблем — _.",
  "_ — це новий чорний.",
  "Замість кава з молоком, бариста запропонував мені _ з молоком.",
  "Перше, що я зроблю, коли виграю мільйон — куплю _.",
  "Моя дієта складається виключно з _ та каяття.",
  "Наша армія непереможна, бо у неї є _.",
  "За конституцією кожен українець має право на _.",
  "Найкращий спосіб привернути увагу на вечірці — принести _.",
  "Мій термін бажань на цей рік: менше _, більше щастя.",
  "Хіромант передбачив мені _ на лінії долі.",
  "Нобелівську премію цього року дали за відкриття зв'язку між щастям і _.",
  "_ — ось що я побачив у холодильнику о третій ночі.",
  "Якщо хочеш стати успішним, щоранку читай лекцію _ у дзеркало.",
  "Мій вчитель математики пах _, і це пояснює багато речей.",
  "Президент підписав указ про обов'язкове вивчення _ у школах.",
  "Науковці виявили, що _ покращує пам'ять на 300%.",
  "Мій геній — це поєднання хаосу та _.",
  "На конкурсі краси перемогла та, хто вміє робити _.",
  "Головне у відносинах — це честь, повага та _.",
  "Від чого залежить курс гривні? Від _, звісно.",
  "Кожна українська бабуся знає: на всі хвороби допомагає _.",
  "Мій фітнес-тренер заборонив мені _, але я ігнорую.",
  "Інопланетяни прилетіли, побачили _, і одразу полетіли геть.",
  "Прем'єр-міністр запевнив: «Ми повністю контролюємо _.»",
  "Знайдено стародавній рецепт безсмертя. Головний інгредієнт — _.",
  "Моя бабуся брала на зиму 40 банок варення і _.",
  "Якщо вам сумно, просто подивіться на _.",
  "Головна різниця між містом і селом — це наявність _.",
  "Дорогий Санта, цього року мені потрібне лише одне — _.",
  "Я записався до психолога через _. Це змінило моє життя.",
  "Митники на кордоні конфіскували_ і нікому не сказали чому.",
  "Мій початковий план на відпустку: _, _, і трохи відпочинку.",
  "У заяві на роботу я вказав, що вмію _, але хтозна.",
  "Оголошення: терміново шукаємо людину, що вміє поводитися з _.",
  // two-blank
  "Мій перший фільм: «_ та _: Нескінченна історія».",
  "Рецепт успіху: одна ложка _, щіпка _ і молитва.",
  // more single-blank
  "Якби _ було спортом, то я б точно взяв золото.",
  "Перш ніж померти, я хочу спробувати _.",
  "Моя муза — це _. Без неї я нічого не можу.",
  "Чому я не сплю о 4 ранку? Бо думаю про _.",
  "Найкраще, що я коли-небудь купував — це _.",
  "Єдина річ, яка мене ще тримає — це _.",
  "Школа не навчила мене _, але вулиця навчила.",
  "Лікар сказав, що якщо я не кину _, то доживу до 40.",
  "Перша заповідь сучасного українця: не тинятися без _.",
  "На виставці сучасного мистецтва головним експонатом був _.",
  "Мій коучинг-гуру вчить: «Вранці їж _, ввечері кидай звички.»",
  "Відеоблогер набрав 1 мільйон підписників, знімаючи _.",
  "Ця нова дієта передбачає відмову від _ упродовж 30 днів.",
  "Мій терапевт з'ясував, що причиною всього є _.",
  "Мій дитячий секрет: я ховав _ під матрацом.",
  "_ — це єдина мова, яку розуміють всі.",
  "Наш орендодавець заборонив у квартирі лише одне — _.",
  "ТОП-1 річ, яку я точно не напишу в CV — це вміння _.",
  "Астролог передбачив, що _ прийде до мого життя у четвер.",
  "Дослідження виявило, що _ підвищує рівень щастя на 47%.",
  "Нова функція в Дії: тепер можна задекларувати _.",
  "Моя улюблена мова програмування — це _, але тільки вночі.",
  "Усі катастрофи починаються з _.  Це науково доведено.",
  "На прийомі у нотаріуса перевіряли власність на _.",
  "Щоб стати депутатом, достатньо мати _ і хороші зв'язки.",
  "Після третьої кави я починаю думати про _.",
  "Загублено: _, нагорода тому, хто знайде.",
  "Моя вчителька літератури плакала, коли читала про _.",
  "Сезон _ відкрито. Мисливська ліцензія не потрібна.",
  "Мій улюблений спосіб розслабитися — _ і тиша.",
  "Нова освітня програма включає обов'язковий курс «_».",
  "Мій дідусь воював з _. І переміг.",
  "Офіційна причина затримки поїзда: «технічні проблеми з _.»",
  "Науковці врешті-решт пояснили, чому кіт ігнорує _ хазяїна.",
  "Магазин «КПМ» провів акцію: при купівлі _ — _ в подарунок.",
  "Цей документальний фільм змінив моє ставлення до _.",
  "Якби я писав автобіографію, вона б починалась зі слів: «Усе почалося через _.»",
  "Гарантія щастя: просто уникай _.",
  "Конфіскат звичайного дня: одна копія _, дві надії і трохи сорому.",
];

export const whiteCards: string[] = [
  // people/characters
  "Зеленський у піжамі",
  "Бабуся з борщем",
  "П'яний депутат",
  "Суворий сантехнік",
  "Блогер-дієтолог",
  "Котик Зефір",
  "Покровитель корупції",
  "Чиновник на Bentley",
  "IT-шник без сну",
  "Вічний студент",
  "Бариста-філософ",
  "Тітонька Люда з порадами",
  "Дядько Вася з дачею",
  "Мем-лорд інтернету",
  "Пенсіонер у чаті ОСББ",
  "Патріотичний тролейбус",
  "Незадоволений клієнт",
  "Психолог без ліцензії",
  "Ветеран сусідських війн",
  "Лікар сімейної медицини",
  // food & drink
  "Борщ із часником",
  "Вареники з картоплею",
  "Сало в шоколаді",
  "Кава за 80 гривень",
  "Протухлий холодець",
  "Банка з огірками",
  "Котлета по-київськи",
  "Гречка на три тижні",
  "Знежирений кефір",
  "Паска без родзинок",
  "Пиріжок із нічого",
  "Куліш на вогнищі",
  "Медівник від бабусі",
  "Смузі з буряка",
  "Чай із чебрецем",
  "Горілка без закуски",
  "Пляцок зі Львова",
  "Квасоля з лавровим листом",
  "Тушонка 2003 року",
  "Доширак із гордістю",
  // places & infrastructure
  "Яма на дорозі",
  "Черга у ЖЕКу",
  "Ліфт у хрущовці",
  "Укрпошта в понеділок",
  "Маршрутка без дверцят",
  "Ринок із запахом",
  "Підвал із картоплею",
  "Обласна рада",
  "Сільський стадіон",
  "Метро у годину пік",
  "Дитячий майданчик з іржею",
  "Будівля «під реконструкцію»",
  "Парк із лавочками без дощок",
  "Пральня на першому поверсі",
  "Генератор на балконі",
  // abstract concepts
  "Безкінечний оптимізм",
  "Квантова прокрастинація",
  "Тихе відчай",
  "Раптова патріотична сльоза",
  "Синдром самозванця",
  "Глибока лінь",
  "Фінансова грамотність",
  "Колективна відповідальність",
  "Стратегічне невігластво",
  "Поміркована паніка",
  "Хаотична енергія",
  "Неочікувана мудрість",
  "Системний збій",
  "Тотальне непорозуміння",
  "Екзистенційна нудьга",
  "Легкий жах",
  "Моральна гнучкість",
  "Помилкова впевненість",
  "Публічний сором",
  "Вічне очікування",
  // technology & modern life
  "Відключення світла",
  "Wi-Fi сусіда",
  "Дедлайн учора",
  "Зум-колл у піжамі",
  "Чат-бот без мозку",
  "Криптовалюта батька",
  "Оновлення Windows",
  "Акаунт у TikTok",
  "Нескінченний скрол",
  "Дропшипінг без продажів",
  "Пароль «password123»",
  "Сповіщення о 3 ночі",
  "Excel на 5000 рядків",
  "Акумулятор 1%",
  "Фейковий відгук",
  "Спам від банку",
  "Втрачений кабель зарядки",
  "Нова \"революційна\" апка",
  "Публічний Wi-Fi",
  "Скріншот особистого переписування",
  // nature & animals
  "Злий гусак",
  "Бездомний їжак",
  "Корова на трасі",
  "Пес із сумним поглядом",
  "Зозуля без відповіді",
  "Осінній дощ у вересні",
  "Весняний бруд",
  "Перший сніг у квітні",
  "Комар у вухо",
  "Мишка у хліборобці",
  "Курка-рекордсменка",
  "Кріт на городі",
  "Оса в кімнаті",
  "Жаби після дощу",
  "Павутина на лиці",
  // health & body
  "Грип у серпні",
  "Черга до лікаря",
  "Народна медицина",
  "Горщик з геранню",
  "Лускатне коліно",
  "Болить «ось тут»",
  "Запис за місяць наперед",
  "Таблетка «на всяк випадок»",
  "Самолікування YouTube",
  "Алергія на повітря",
  "Вітамін D у дефіциті",
  "Кров'яний тиск дідуся",
  "Маска на підборідді",
  "Дієта з понеділка",
  "Заняття йогою раз на рік",
  // politics & society
  "Реформа реформ",
  "Прес-конференція ні про що",
  "Антикорупційний корупціонер",
  "Євроінтеграція по-нашому",
  "Субсидія на мрії",
  "Бюджетний дефіцит душі",
  "Популістське обіцянко",
  "Опозиція всередині опозиції",
  "Виборчий пиріг",
  "Комітет з питань комітетів",
  // culture & entertainment
  "Серіал про закохану лікарку",
  "Квест «знайди квитанцію»",
  "Весілля на 200 осіб",
  "Хрестини наприкінці серпня",
  "Концерт у ДК",
  "Дискотека 90-х",
  "Телебачення після 22:00",
  "Книжковий ярмарок у дощ",
  "Кіно в маршрутці",
  "Народна пісня після третьої",
  // work & money
  "Зарплата «в конверті»",
  "Відпустка без відпустки",
  "Кар'єрна стеля",
  "Корпоратив в офісі",
  "Звільнення по-тихому",
  "Аванс до авансу",
  "Робота вдома без дому",
  "Колега-шпигун",
  "Підвищення «наступного кварталу»",
  "Бонус словами",
  // extra vivid phrases
  "Цілодобове нічого",
  "Несподіваний вихідний",
  "Чужий собака на дивані",
  "Повернення блудного wifi",
  "Мокрі шкарпетки",
  "Забутий день народження",
  "Помилковий будильник",
  "Хліб без пакета",
  "Дрібні монети в кишені",
  "Старий календар на стіні",
  "Ключі, яких немає",
  "Порожній холодильник і надія",
  "Квіти без приводу",
  "Прострочена реклама",
  "Вмивальник без пробки",
  "Пластиковий пакет із пакетами",
  "Інструкція без перекладу",
  "Зламана парасолька в дощ",
  "Пляшка без відкривачки",
  "Перефотографований борщ",
  // more abstract / funny
  "Надмірна порядність",
  "Публічне зізнання",
  "Вчасна помста",
  "Дитячий trauma",
  "Незаслужений комплімент",
  "Чужа думка о 2 ночі",
  "Напружена тиша",
  "Раптова мудрість",
  "Сусідський дриль у неділю",
  "Дозвіл без сенсу",
  "Обіцяний ремонт",
  "Вічний план «з понеділка»",
  "Сумна флейта у підземці",
  "Каша з нічого",
  "Безліч порад від усіх",
  "Образа без слів",
  "Ностальгія за тим, чого не було",
  "Самотність у натовпі",
  "Незручна правда",
  "Марна надія",
  "Велике роз'яснення нічого",
  "Мовчазна згода",
  "Чиясь проблема",
  "Питання без відповіді",
  "Пустий жест",
  // Ukrainian specifics
  "Мова «та й мова»",
  "Дух козацький",
  "Трипільська культура",
  "Борщ як ідентичність",
  "Вишиванка в понеділок",
  "Степ без кінця",
  "Хата скраю",
  "Калина при дорозі",
  "Соняшник у вазі",
  "Небо в алмазах",
  "Кобзар під подушкою",
  "Клімат-біженець із Херсона",
  "Вареник-символ нації",
  "Мазепа і легенди",
  "Рушник вишиваний",
  "Пісня без слів",
  "Хліб-сіль на рушнику",
  "Свічка в темряві",
  "Тризуб на лобі",
  "Вогонь у серці",
  // more pop culture
  "Байрактар у подарунок",
  "Черга за паляницею",
  "Заєць «Джавелін»",
  "Мем про понеділок",
  "Генератор щастя",
  "Розклад без сенсу",
  "Безкінечна реформа ЖКГ",
  "Сонячна батарея на хрущовці",
  "Пауербанк для душі",
  "Зарядка в кафе",
  "Тепловий насос і молитва",
  "Підвал як стиль życia",
  "Мобілізаційна повістка",
  "Броня для програміста",
  "Волонтерський борщ",
  "Дрон із прапором",
  "Позиційна оборона стосунків",
  "Зарплата у долларах i мрії в гривнях",
  "Черга на е-черзі",
  "Перевірений ЗСУ",
  // extra for padding to 420+
  "Кіт Патрон",
  "Бойова медикиня",
  "Нічна варта",
  "Укриття в метро",
  "Тривога о 5 ранку",
  "Відключений газ",
  "Запас гречки",
  "Батько-героїня",
  "Онук-програміст",
  "Справжній патріот",
  "Фейсбук-активіст",
  "Стратегічний запас сала",
  "Обласний чиновник",
  "Тендерний комітет",
  "Незалежна незалежність",
  "Позасистемний підхід",
  "Ліберальний консерватор",
  "Прогресивна традиція",
  "Цифрова держава в аналоговому селі",
  "Бюрократична магія",
  // extra additions for 400+
  "Ранковий подкаст ні про що",
  "Аудіокнига без фіналу",
  "Квартира без паркування",
  "Сусід-реставратор",
  "Безмовний крик всередині",
  "Незаплановане свято",
  "Причина не вставати",
  "Спонтанний похід у супермаркет",
  "Зламаний каблук рішення",
  "Одна зайва таблетка",
  "Зустріч із собою",
  "Справжній сигнал тривоги",
  "Плач у ванній",
  "Щасливе непорозуміння",
  "Кілька невдалих спроб",
  "Офіційний вибачення",
  "Подарунок без поводу",
  "Неоголошений конкурс краси",
  "Недосяжна планка",
  "Прихований талант",
  "Корисна звичка на 3 дні",
  "Вислів про вихідні",
  "Мигдальне молоко без мигдалю",
  "Непотрібна нотатка",
  "Хаотична ранкова рутина",
  "Семінар у сні",
  "Раптова відверта розмова",
  "Незакінчений твір",
  "Тихий скандал",
  "Необов'язковий урок",
  "Незапланована перерва",
  "Запізнення з виправданням",
  "Повторна помилка",
  "Заспаний вибір",
  "Принципова відмова",
  "Незрозумілий жарт",
  "Ненормований день",
  "Спонтанна покупка",
  "Безглузда суперечка",
  "Третій зайвий на вечірці",
  "Легка образа",
  "Симптом без хвороби",
  "Посмішка крізь сльози",
  "Щоденний страх",
  "Неочікуване рішення",
  "Відкладена розмова",
  "Забутий код відгуку",
  "Хибна тривога",
  "Зайвий коментар",
  "Неявна образа",
  "Хронічна втома",
  "Неочевидний висновок",
  "Вчасна допомога",
  "Запізніле розкаяння",
  "Непотрібна порада",
  "Ненавмисна правда",
  "Цілеспрямована випадковість",
  "Невиправданий ризик",
  "Довгоочікувана відповідь",
  "Вдале непорозуміння",
  "Надзвичайно звичайний день",
  "Зупинка у нікуди",
  "Половина рішення",
  "Ввічлива неправда",
  "Неповна картина",
  "Крок назад перед стрибком",
  "Марна відмовка",
  "Гідне прощання",
  "Відмова від відмови",
  "Невчасний сміх",
  "Принципова дрібниця",
  "Незручна пауза",
  "Спільна мовчанка",
  "Безмовний дорікання",
  "Тихе примирення",
  "Несподіваний союзник",
  "Переможений переможець",
  "Порожня перемога",
  "Непотрібний ультиматум",
  "Незрозуміла лояльність",
  "Приховане задоволення",
  "Таємна заздрість",
  "Щира неправда",
  "Половина правди",
  "Повна нісенітниця",
  "Відверта брехня",
  "Чесна маніпуляція",
  "Жорстока доброта",
  "Ніжна грубість",
  "Солодка помста",
  "Гіркий успіх",
  "Дорога безкоштовна порада",
  "Незамінна деталь",
  "Термінова тиша",
  "Плановий хаос",
  "Свідомий самообман",
  "Добровільна поневіра",
  "Раціональна паніка",
  "Організована анархія",
  "Керований безлад",
  "Впорядкований хаос",
  "Мирна революція",
  "Тихий бунт",
  "Скромна амбіція",
  "Величне банальне",
  "Глибока поверховість",
  "Тонка грубість",
  "Штучна щирість",
  "Природна штучність",
  "Тепла байдужість",
  "Холодна пристрасть",
  "Живий труп",
  "Мертва ідея",
  "Порожній повний склянки",
  "Велика маленька проблема",
  "Важка легкість",
  "Легка важкість",
  "Темне просвітлення",
  "Яскрава темрява",
  "Гучна тиша",
  "Мовчазний крик",
  "Впевнена невизначеність",
  "Стабільна нестабільність",
  // final padding
  "Обіцянка без терміну",
  "Шрам без болю",
  "Жаль без жалості",
  "Сміх без причини",
  "Думка без слів",
  "Слово без думки",
  "Дія без наслідків",
  "Наслідок без дії",
  "Питання без запитання",
  "Відповідь ні на що",
  "Мрія без адреси",
  "Адреса без мрії",
  "Час без часу",
  "Місце без місця",
  "Щось дуже важливе",
  "Ніщо з великої літери",
  "Абсолютно все",
];

export const blackCardsEn: string[] = [
  "Scientists finally discovered what causes depression. It's _.",
  "My grandfather always said: 'The worst thing in life is _.'",
  "For my birthday they gave me _. Best gift ever.",
  "_ is what truly unites Ukrainians.",
  "Breaking news: Parliament has voted to legalize _.",
  "Why do I always forget to buy bread? Because I'm thinking about _.",
  "Nutritionists recommend replacing sugar with _.",
  "A new startup promises to solve all humanity's problems with _.",
  "My mom thinks I'm doing _, but actually I'm playing cards.",
  "According to polls, 73% of people fear _ the most.",
  "My cat stares at me like it knows about _.",
  "My will states: 'Instead of flowers, please bring _.'",
  "The new currency of the future is _.",
  "Before sleep I pray that _ disappears from my life.",
  "The secret to a long marriage: never mention _.",
  "AI learned everything human, including _.",
  "My therapist said _ is the root of all my problems.",
  "_ is the new black.",
  "Instead of a latte the barista offered me _ with milk.",
  "The first thing I'll do when I win a million: buy _.",
  "My diet consists entirely of _ and regret.",
  "Our army is unBeatable because it has _.",
  "By law, every citizen has a right to _.",
  "The best way to grab attention at a party: bring _.",
  "My one wish this year: less _, more happiness.",
  "The palm reader saw _ on my life line.",
  "This year's Nobel Prize went to the person who discovered the link between happiness and _.",
  "_ is what I found in the fridge at 3 am.",
  "To become successful, give a speech about _ to your mirror every morning.",
  "My math teacher smelled of _, and that explains a lot.",
  "The president signed a decree making _ mandatory in schools.",
  "Scientists found that _ improves memory by 300%.",
  "My genius is a blend of chaos and _.",
  "The beauty contest was won by whoever could do _.",
  "The foundation of any relationship: honor, respect, and _.",
  "What determines the exchange rate? _ of course.",
  "Every grandma knows: _ cures everything.",
  "My fitness trainer banned _, but I ignore it.",
  "Aliens arrived, saw _, and immediately left.",
  "The Prime Minister assured: 'We have _ fully under control.'",
  "An ancient immortality recipe was found. Key ingredient: _.",
  "My grandma stockpiled 40 jars of jam and _.",
  "Feeling sad? Just look at _.",
  "The main difference between city and countryside: the presence of _.",
  "Dear Santa, this year I only need one thing: _.",
  "I visited a therapist because of _. Life-changing.",
  "Customs agents confiscated _ and told no one why.",
  "My original vacation plan: _, _, and some rest.",
  "In my job application I listed _ as a skill.",
  "We urgently need someone who knows how to handle _.",
  "My debut film: '_ and _: An Endless Story.'",
  "Recipe for success: one spoon of _, a pinch of _, and prayer.",
  // more EN black cards
  "If _ were a sport I'd take gold.",
  "Before I die I want to try _.",
  "My muse is _. Without it I'm nothing.",
  "Why am I awake at 4am? Because I'm thinking about _.",
  "The best thing I've ever bought is _.",
  "The only thing still keeping me going is _.",
  "School never taught me _, but the street did.",
  "The doctor said if I don't quit _ I'll reach 40.",
  "The first commandment of the modern citizen: never leave home without _.",
  "The star exhibit at the contemporary art gallery was _.",
  "My life coach teaches: 'Eat _ in the morning, drop bad habits at night.'",
  "A YouTuber hit a million subscribers filming _.",
  "This new diet requires you to give up _ for 30 days.",
  "My therapist figured out that _ is the cause of everything.",
  "My childhood secret: I kept _ under the mattress.",
  "_ is the only language everyone understands.",
  "Our landlord only banned one thing in the apartment — _.",
  "The one thing I'll never put on my CV: skill of _.",
  "The astrologer predicted _ would enter my life on Thursday.",
  "Research shows that _ increases happiness levels by 47%.",
  "There's a new government app feature: now you can declare _.",
  "My favourite programming language is _, but only at night.",
  "All disasters begin with _. Scientifically proven.",
  "At the notary they verified ownership of _.",
  "To become an MP, all you need is _ and good connections.",
  "After my third coffee I start thinking about _.",
  "Lost: _. Reward offered to whoever finds it.",
  "My literature teacher cried when she read about _.",
  "The _ season is open. No hunting licence required.",
  "My favourite way to unwind: _ and silence.",
  "The new curriculum includes a compulsory course: '_'.",
  "My grandfather fought against _. And won.",
  "Official reason for train delay: 'technical problems with _.'",
  "Scientists finally explained why the cat ignores its owner's _.",
  "The shop ran a deal: buy _ and get _ free.",
  "This documentary changed my opinion about _.",
  "If I wrote an autobiography it'd open with: 'It all started because of _.'",
  "Guaranteed happiness: just avoid _.",
  "Official confiscation of an average day: one copy of _, two hopes, and a bit of shame.",
];

export const whiteCardsEn: string[] = [
  "Zelensky in pajamas", "Grandma with borscht", "Drunk MP", "Strict plumber", "Diet blogger",
  "Cat named Biscuit", "Champion of corruption", "Official in a Bentley", "Sleep-deprived dev",
  "Eternal student", "Philosopher barista", "Aunt Linda's advice", "Uncle Bob's garden",
  "Internet meme lord", "Pensioner in the building chat", "Patriotic trolleybus",
  "Unsatisfied customer", "Unlicensed therapist", "Veteran of neighbor wars",
  "Family doctor", "Borscht with garlic", "Dumplings with potatoes", "Lard in chocolate",
  "Coffee at $2", "Spoiled aspic", "A jar of pickles", "Chicken Kyiv", "Buckwheat for 3 weeks",
  "Fat-free kefir", "Easter bread without raisins", "A pie from nothing", "Field soup on campfire",
  "Honey cake from grandma", "Beetroot smoothie", "Herbal tea", "Vodka with no snack",
  "Pastry from Lviv", "Bean stew with bay leaf", "Canned meat from 2003", "Instant noodles with pride",
  "A pothole on the road", "Queue at the housing office", "Elevator in a Khrushchyovka",
  "Post office on Monday", "Minibus without doors", "Market with a smell",
  "Basement with potatoes", "Regional council", "Village stadium", "Subway at rush hour",
  "Rusty playground", "Building 'under renovation'", "Park bench without planks",
  "Laundry room on the ground floor", "Generator on the balcony", "Endless optimism",
  "Quantum procrastination", "Quiet despair", "Sudden patriotic tear",
  "Impostor syndrome", "Deep laziness", "Financial literacy",
  "Collective responsibility", "Strategic ignorance", "Moderate panic",
  "Chaotic energy", "Unexpected wisdom", "System failure", "Total misunderstanding",
  "Existential boredom", "Mild dread", "Moral flexibility", "Misplaced confidence",
  "Public shame", "Eternal waiting", "Power outage", "Neighbor's Wi-Fi",
  "Yesterday's deadline", "Zoom call in pajamas", "Brainless chatbot",
  "Dad's crypto portfolio", "Windows update", "TikTok account",
  "Infinite scroll", "Dropshipping with zero sales", "Password 'password123'",
  "3am notification", "Excel with 5000 rows", "1% battery",
  "Fake review", "Bank spam", "Lost charging cable",
  "New 'revolutionary' app", "Public Wi-Fi", "Screenshot of a private chat",
  "Angry goose", "Stray hedgehog", "Cow on the highway", "Dog with a sad look",
  "Cuckoo with no answer", "September autumn rain", "Spring mud",
  "April first snow", "Mosquito in your ear", "Mouse in the pantry",
  "Record-breaking hen", "Mole in the garden", "Wasp in the room",
  "Frogs after rain", "Spiderweb to the face", "Summer flu",
  "Doctor's waiting room", "Folk medicine", "Flowerpot with geranium",
  "Creaky knee", "It hurts 'right here'", "Appointment in a month",
  "Just-in-case pill", "YouTube self-diagnosis", "Allergy to air",
  "Vitamin D deficiency", "Grandpa's blood pressure", "Mask on the chin",
  "Diet starting Monday", "Yoga once a year", "Reform of reforms",
  "Press conference about nothing", "Anti-corruption corruptor",
  "EU integration our way", "Subsidy for dreams", "Budget deficit of the soul",
  "Populist promise", "Opposition within the opposition", "Electoral pie",
  "Committee for committees", "Medical drama series", "Quest to find a receipt",
  "Wedding for 200 people", "Late August christening", "Concert at the culture house",
  "90s disco", "TV after 10pm", "Book fair in the rain", "Movie in the minibus",
  "Folk song after the third round", "Envelope salary", "Vacation without vacation",
  "Career ceiling", "Christmas party in the office", "Quiet firing",
  "Advance before the advance", "Working from home without a home",
  "Office spy", "Raise 'next quarter'", "Bonus in words",
  "Doing nothing all night", "Unexpected day off", "Someone else's dog on the couch",
  "The return of the prodigal Wi-Fi", "Wet socks", "Forgotten birthday",
  "Wrong alarm", "Bread without bag", "Coins in your pocket",
  "Old calendar on the wall", "Keys that are nowhere", "Empty fridge and hope",
  "Flowers for no reason", "Expired ad", "Washbasin without a plug",
  "Plastic bag of plastic bags", "Manual with no translation", "Broken umbrella in the rain",
  "Bottle without opener", "Over-photographed borscht", "Excessive decency",
  "Public confession", "Timely revenge", "Childhood trauma",
  "Undeserved compliment", "Someone's opinion at 2am", "Tense silence",
  "Sudden wisdom", "Neighbor's drill on Sunday", "Meaningless permission",
  "Promised renovation", "Eternal 'starting Monday' plan", "Sad flute in the subway",
  "Soup from nothing", "Endless advice from everyone", "Wordless offense",
  "Nostalgia for something that never happened", "Loneliness in a crowd",
  "Uncomfortable truth", "False hope", "Big explanation of nothing",
  "Silent consent", "Someone else's problem", "Question with no answer",
  "Empty gesture", "The spirit of the Cossacks", "Borscht as identity",
  "Embroidered shirt on Monday", "Cat Patron", "Combat medic",
  "Night watch", "Power outage at 5am", "Supply of buckwheat",
  "Father-heroine", "Grandson-programmer", "True patriot",
  "Facebook activist", "Strategic lard reserve", "Regional official",
  "Tender committee", "Independent independence", "Out-of-system approach",
  "Liberal conservative", "Progressive tradition", "Digital state in an analog village",
  "Bureaucratic magic", "Bayraktar as a gift", "Queue for bread",
  "Missile interception", "Monday meme", "Happiness generator",
  "Pointless schedule", "Endless utility reform", "Solar panel on a Soviet building",
  "Powerbank for the soul", "Charging up at the café", "Heat pump and prayer",
  "Basement as a lifestyle", "Draft notice", "Deferment for the programmer",
  "Volunteer borscht", "Drone with a flag", "Positional defense of a relationship",
  "Dollar salary and hryvnia dreams", "Queue in the e-queue", "Vetted by the army",
  // extras to reach 400+
  "Morning podcast about nothing", "Audiobook without an ending", "Apartment without parking",
  "Neighbour restoring furniture", "Soundless scream inside", "Unplanned holiday",
  "Reason not to get up", "Spontaneous supermarket trip", "Broken heel of a decision",
  "One extra pill", "Meeting with yourself", "Real alarm signal",
  "Crying in the bathroom", "Happy misunderstanding", "Several failed attempts",
  "Official apology", "Gift for no reason", "Undeclared beauty contest",
  "Unreachable bar", "Hidden talent", "Healthy habit lasting 3 days",
  "Weekend quote", "Almond milk without almonds", "Useless note",
  "Chaotic morning routine", "Seminar in a dream", "Sudden candid conversation",
  "Unfinished essay", "Quiet scandal", "Unnecessary lesson",
  "Unplanned break", "Late excuse", "Repeated mistake",
  "Sleepy choice", "Principled refusal", "Incomprehensible joke",
  "Unnormalized workday", "Spontaneous purchase", "Pointless argument",
  "Uninvited third wheel", "Mild offense", "Symptom without illness",
  "Smile through tears", "Daily fear", "Unexpected decision",
  "Postponed conversation", "Forgotten promo code", "False alarm",
  "Unnecessary comment", "Implicit offense", "Chronic fatigue",
  "Non-obvious conclusion", "Help at the right time", "Belated regret",
  "Unsolicited advice", "Unintentional truth", "Purposeful coincidence",
  "Unjustified risk", "Long-awaited reply", "Fortunate misunderstanding",
  "Extraordinarily ordinary day", "Stop in the middle of nowhere", "Half a decision",
  "Polite lie", "Incomplete picture", "Step back before a leap",
  "Lame excuse", "Dignified farewell", "Refusal to refuse",
  "Mistimed laughter", "Principled trifle", "Awkward pause",
  "Shared silence", "Silent reproach", "Quiet reconciliation",
  "Unexpected ally", "Defeated champion", "Empty victory",
  "Unnecessary ultimatum", "Inexplicable loyalty", "Hidden pleasure",
  "Secret envy", "Sincere lie", "Half the truth",
  "Total nonsense", "Honest manipulation", "Cruel kindness",
  "Gentle rudeness", "Sweet revenge", "Bitter success",
  "Expensive free advice", "Irreplaceable detail", "Urgent silence",
  "Planned chaos", "Conscious self-deception", "Voluntary bondage",
  "Rational panic", "Organised anarchy", "Controlled disorder",
  "Orderly chaos", "Peaceful revolution", "Quiet rebellion",
  "Modest ambition", "The mundanely magnificent", "Deep shallowness",
  "Subtle rudeness", "Artificial sincerity", "Natural artificiality",
  "Warm indifference", "Cold passion", "Living corpse",
  "Dead idea", "Half-empty full glass", "Big small problem",
  "Heavy lightness", "Light heaviness", "Dark enlightenment",
  "Bright darkness", "Loud silence", "Mute scream",
  "Confident uncertainty", "Stable instability",
  // final EN padding
  "Promise with no deadline", "Scar without pain", "Regret without remorse",
  "Laughter for no reason", "Thought without words", "Words without thought",
  "Action with no consequences", "Consequence with no action",
  "Question without a question", "Answer to nothing",
  "Dream with no address", "Address with no dream",
  "Time without time", "Place without place",
  "Something very important", "Nothing with a capital N",
  "Absolutely everything", "Something else entirely",
  "The thing no one talks about", "That one embarrassing memory",
  "A deeply reasonable fear", "Irrational calm",
  "Budget infinity stones", "Borrowed time and bad decisions",
  "Mild inconvenience energy", "The audacity of it all",
  "Unearned confidence", "Strategic incompetence",
  "Weaponised helplessness", "Professional procrastinator",
  "Certified overthink", "Galaxy-brain conclusion",
  "Vibes without substance", "Substance without vibes",
  "The forbidden nap", "Aggressive mediocrity", "Terminal chill",
];

export function shuffleDeck<T>(deck: T[]): T[] {
  const result = [...deck];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    [result[i], result[j]] = [result[j]!, result[i]!];
  }
  return result;
}

export function dealCards(
  deck: string[],
  count: number,
): { hand: string[]; remaining: string[] } {
  const hand = deck.slice(0, count);
  const remaining = deck.slice(count);
  return { hand, remaining };
}
